.llvmpipe-test:
  extends:
    - .llvmpipe-rules
  variables:
    LIBGL_ALWAYS_SOFTWARE: "true"
    GALLIUM_DRIVER: "llvmpipe"
    FLAKES_CHANNEL: "#mesa-swrast-ci"
    GPU_VERSION: llvmpipe

.llvmpipe-piglit-cl:
  extends:
    - .test-cl
    - .deqp-test
    - .llvmpipe-test
  variables:
    LP_NUM_THREADS: 1
    PIGLIT_PROFILES: cl

llvmpipe-piglit-clover:
  extends:
    - .llvmpipe-piglit-cl
    - .llvmpipe-clover-rules
  needs:
    - debian-clover-testing
    - debian/x86_test-gl
  variables:
    LP_CL: 1
    DEQP_SUITE: llvmpipe-clover
    GPU_VERSION: llvmpipe-clover

llvmpipe-piglit-rusticl:
  extends:
    - .llvmpipe-piglit-cl
    - .llvmpipe-rusticl-rules
  needs:
    - debian-rusticl-testing
    - debian/x86_test-gl
  variables:
    RUSTICL_ENABLE: "llvmpipe"
    DEQP_SUITE: llvmpipe-rusticl
    GPU_VERSION: llvmpipe-rusticl

llvmpipe-traces:
  extends:
    - .test-gl
    - .piglit-traces-test
    - .llvmpipe-test
  variables:
    EGL_PLATFORM: "surfaceless"
    PIGLIT_REPLAY_DESCRIPTION_FILE: "${CI_PROJECT_DIR}/install/traces-llvmpipe.yml"
    PIGLIT_REPLAY_DEVICE_NAME: "gl-vmware-llvmpipe"
    PIGLIT_RESULTS: "llvmpipe-replay"

.llvmpipe-deqp-test:
  variables:
    GALLIVM_PERF: "nopt"
  extends:
    - .test-gl
    - .deqp-test
    - .llvmpipe-test

llvmpipe:
  tags:
    - mesa-swrast
  variables:
    DEQP_SUITE: llvmpipe
    XDG_RUNTIME_DIR: /run/user
  extends: .llvmpipe-deqp-test
  script:
    - mkdir -p $XDG_RUNTIME_DIR
    - LD_LIBRARY_PATH=`pwd`/install weston -Bheadless-backend.so -Swayland-0 &
    - LD_LIBRARY_PATH=`pwd`/install WAYLAND_DISPLAY=wayland-0 xvfb-run --server-args='-noreset' install/deqp-runner.sh

llvmpipe-deqp-asan:
  variables:
    DEQP_SUITE: llvmpipe-asan
    GPU_VERSION: llvmpipe-asan
    DEQP_FRACTION: 10
    # Don't use threads inside llvmpipe, we've already got all cores
    # busy at the deqp-runner level, and we don't want to overload fd.o
    # shared runners
    LP_NUM_THREADS: 0
  extends: .llvmpipe-deqp-test
  needs:
    - debian/x86_test-gl
    - debian-testing-asan
