.gm20b-test:
  extends:
    - .baremetal-test-arm64
    - .nouveau-rules
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    BM_BOOTFS: /baremetal-files/jetson-nano/
    BM_CMDLINE: "console=ttyS0,115200n8 rw nfsrootdebug init=/init"
    FLAKES_CHANNEL: "#nouveau-ci"
    GPU_VERSION: nouveau-gm20b
    # We package these as modules so that we can load them after the firmware is
    # available on NFS.
    HWCI_KERNEL_MODULES: tegra-drm,nouveau
  script:
    - ./install/bare-metal/poe-powered.sh
  tags:
    - google-nouveau-jetson-nano

# Single Jetson Nano board at anholt's house.
gm20b-gles-full:
  extends:
    - .gm20b-test
    - .test-manual-mr
  timeout: 2h
  variables:
    DEQP_SUITE: nouveau-gm20b
    # 4 CPUs, but spawn a couple extra threads to make sure they stay busy while
    # some are waiting for the GPU.
    FDO_CI_CONCURRENT: 6

gm20b-gles:
  extends:
    - gm20b-gles-full
  timeout: 60m
  variables:
    DEQP_FRACTION: 10
