.d3d12-test:
  extends:
    - .build-windows
    - .use-windows_test_vs2019
    - .glon12-test-rules
  stage: layered-backends
  dependencies:
    - windows-vs2019
  needs:
    - windows-vs2019
    - windows_test_vs2019
  variables:
    GIT_STRATEGY: none # testing doesn't build anything from source
    GALLIUM_DRIVER: d3d12
    WGL_DISABLE_ERROR_DIALOGS: "true"
    D3D12_AGILITY_RELATIVE_PATH: "D3D12\\"
    D3D12_AGILITY_SDK_VERSION: 706

.d3d12-test-piglit:
  extends:
    - .d3d12-test
  script:
    - . _install/piglit_run.ps1
  artifacts:
    when: on_failure
    name: "mesa_${CI_JOB_NAME}"
    paths:
      - summary/
      - result.txt

test-d3d12-quick_gl:
  extends:
    - .d3d12-test-piglit
  variables:
    PIGLIT_PROFILE: quick_gl
    PIGLIT_RESULTS: "d3d12-quick_gl"
    PIGLIT_TESTS: -x nv_copy_depth_to_color -x glsl-1.30.execution.tex-miplevel-selection -x arb_timer_query.timestamp-get -x max-size -x query.gl_timestamp -x query.time-elapsed -x tes-gs-max-output

test-d3d12-quick_shader:
  extends:
    - .d3d12-test-piglit
  variables:
    PIGLIT_PROFILE: quick_shader
    PIGLIT_RESULTS: "d3d12-quick_shader"
    # These tests crash WARP causing the test suite to timeout, or are flaky
    PIGLIT_TESTS: -x amd_texture_texture4 -x arb_texture_gather -x isoline
